# Generated by Django 2.2.6 on 2019-10-04 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ImageField(blank=True, upload_to='flags')),
                ('name', models.CharField(default='Team', max_length=50, unique=True)),
                ('managers', models.ForeignKey(on_delete='CASCADE', related_name='team_managers', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='team_players', to=settings.AUTH_USER_MODEL)),
                ('requests_users', models.ManyToManyField(blank=True, related_name='team_requests_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
