# Generated by Django 2.2.6 on 2019-10-04 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='team_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
