# Generated by Django 2.2.6 on 2019-10-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191004_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='singleplayerteam',
            field=models.BooleanField(default=False),
        ),
    ]
