# Generated by Django 2.2.6 on 2019-10-03 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='team',
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ManyToManyField(to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='managers',
            unique_together={('team', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='request_teamjoin',
            unique_together={('team', 'user')},
        ),
    ]
