# Generated by Django 2.2.7 on 2019-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_singleplayerteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='defaultteam',
            field=models.BooleanField(default=False),
        ),
    ]
