# Generated by Django 2.2.7 on 2019-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_defaultteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='defaultteam',
        ),
    ]
