# Generated by Django 2.2.7 on 2019-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_defaultteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
