# Generated by Django 2.2.6 on 2019-10-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default='Sponsor', max_length=50, unique=True),
        ),
    ]
