# Generated by Django 2.2.6 on 2019-10-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.IntegerField(blank=True, default=8)),
                ('finished', models.BooleanField(default=False)),
                ('team_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_A', to='teams.Team')),
                ('team_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_B', to='teams.Team')),
                ('turnaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
            options={
                'unique_together': {('team_A', 'turnaj', 'team_B')},
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_A', models.IntegerField(default=0)),
                ('score_B', models.IntegerField(default=0)),
                ('score_optional', models.IntegerField(blank=True, default=0)),
                ('zapas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
            ],
        ),
    ]
