# Generated by Django 2.2.7 on 2019-11-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='score_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_B',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
    ]
