# Generated by Django 2.2.6 on 2019-10-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20191003_2341'),
        ('teams', '0003_auto_20191003_2341'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='zapas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.Match'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team_A', 'turnaj', 'team_B')},
        ),
    ]
