# Generated by Django 2.2.6 on 2019-10-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField(default=0)),
                ('player_count', models.IntegerField(default=8)),
                ('started', models.BooleanField(default=False)),
                ('name', models.CharField(default='Tournament', max_length=50)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
            ],
        ),
    ]
