# Generated by Django 2.2.6 on 2019-10-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsors', '0001_initial'),
        ('teams', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField(default=0)),
                ('player_count', models.IntegerField(default=8)),
                ('started', models.BooleanField(default=False)),
                ('name', models.CharField(default='Tournament', max_length=50)),
                ('singleplayer', models.BooleanField(default=False)),
                ('poradatele', models.ForeignKey(on_delete='CASCADE', related_name='tour_poradatele', to=settings.AUTH_USER_MODEL)),
                ('requests_rozhodci', models.ManyToManyField(blank=True, related_name='tour_requests_rozhodci', to=settings.AUTH_USER_MODEL)),
                ('requests_teams', models.ManyToManyField(blank=True, related_name='tour_requests_teams', to='teams.Team')),
                ('rozhodci', models.ManyToManyField(blank=True, related_name='tour_rozhodci', to=settings.AUTH_USER_MODEL)),
                ('sponsors', models.ManyToManyField(blank=True, related_name='tour_sponsors', to='sponsors.Sponsor')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
                ('teams', models.ManyToManyField(blank=True, related_name='tour_teams', to='teams.Team')),
            ],
        ),
    ]
