# Generated by Django 2.2.6 on 2019-10-03 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20191003_2341'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sponsors', '0002_auto_20191003_2341'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poradatele',
            unique_together={('user', 'turnaj')},
        ),
        migrations.AlterUniqueTogether(
            name='request_rozhodci',
            unique_together={('user', 'turnaj')},
        ),
        migrations.AlterUniqueTogether(
            name='request_tournamentjoin',
            unique_together={('team', 'turnaj')},
        ),
        migrations.AlterUniqueTogether(
            name='rozhodci',
            unique_together={('user', 'turnaj')},
        ),
        migrations.AlterUniqueTogether(
            name='tournament_sponsors',
            unique_together={('sponsor', 'turnaj')},
        ),
        migrations.AlterUniqueTogether(
            name='tournament_teams',
            unique_together={('team', 'turnaj')},
        ),
    ]
